name: Build Docs

# Controls when the action will run
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Grant the github workflow permissions to write files to the repo
permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This one only contains a single job called "build-docs"
  build-docs:
    name: Page Generation

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Checkout doxygen-awesome-css
        uses: actions/checkout@v2
        with:
          # Checks out https://github.com/jothepro/doxygen-awesome-css from github
          repository: jothepro/doxygen-awesome-css
          path: doxygen-awesome-css

      - name: Install doxygen
        run: sudo apt-get install doxygen graphviz -y

      - name: Generate doxygen via doxyfile
        run: doxygen Doxyfile

      - name: Add .nojekyll for github-pages
        run: touch ../MotorMotion-doc/.nojekyll